// Code generated by protoc-gen-go. DO NOT EDIT.
// source: quotes.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type L2OrderBookRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Interval             uint32   `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2OrderBookRequest) Reset()         { *m = L2OrderBookRequest{} }
func (m *L2OrderBookRequest) String() string { return proto.CompactTextString(m) }
func (*L2OrderBookRequest) ProtoMessage()    {}
func (*L2OrderBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa8c397fe3f70398, []int{0}
}

func (m *L2OrderBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2OrderBookRequest.Unmarshal(m, b)
}
func (m *L2OrderBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2OrderBookRequest.Marshal(b, m, deterministic)
}
func (m *L2OrderBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2OrderBookRequest.Merge(m, src)
}
func (m *L2OrderBookRequest) XXX_Size() int {
	return xxx_messageInfo_L2OrderBookRequest.Size(m)
}
func (m *L2OrderBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_L2OrderBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_L2OrderBookRequest proto.InternalMessageInfo

func (m *L2OrderBookRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *L2OrderBookRequest) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *L2OrderBookRequest) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

type L2OrderBookItem struct {
	Price                string   `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Volume               uint64   `protobuf:"varint,2,opt,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2OrderBookItem) Reset()         { *m = L2OrderBookItem{} }
func (m *L2OrderBookItem) String() string { return proto.CompactTextString(m) }
func (*L2OrderBookItem) ProtoMessage()    {}
func (*L2OrderBookItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa8c397fe3f70398, []int{1}
}

func (m *L2OrderBookItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2OrderBookItem.Unmarshal(m, b)
}
func (m *L2OrderBookItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2OrderBookItem.Marshal(b, m, deterministic)
}
func (m *L2OrderBookItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2OrderBookItem.Merge(m, src)
}
func (m *L2OrderBookItem) XXX_Size() int {
	return xxx_messageInfo_L2OrderBookItem.Size(m)
}
func (m *L2OrderBookItem) XXX_DiscardUnknown() {
	xxx_messageInfo_L2OrderBookItem.DiscardUnknown(m)
}

var xxx_messageInfo_L2OrderBookItem proto.InternalMessageInfo

func (m *L2OrderBookItem) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *L2OrderBookItem) GetVolume() uint64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

type L2OrderBook struct {
	Symbol               string               `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bid                  []*L2OrderBookItem   `protobuf:"bytes,2,rep,name=bid,proto3" json:"bid,omitempty"`
	Ask                  []*L2OrderBookItem   `protobuf:"bytes,3,rep,name=ask,proto3" json:"ask,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *L2OrderBook) Reset()         { *m = L2OrderBook{} }
func (m *L2OrderBook) String() string { return proto.CompactTextString(m) }
func (*L2OrderBook) ProtoMessage()    {}
func (*L2OrderBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa8c397fe3f70398, []int{2}
}

func (m *L2OrderBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2OrderBook.Unmarshal(m, b)
}
func (m *L2OrderBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2OrderBook.Marshal(b, m, deterministic)
}
func (m *L2OrderBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2OrderBook.Merge(m, src)
}
func (m *L2OrderBook) XXX_Size() int {
	return xxx_messageInfo_L2OrderBook.Size(m)
}
func (m *L2OrderBook) XXX_DiscardUnknown() {
	xxx_messageInfo_L2OrderBook.DiscardUnknown(m)
}

var xxx_messageInfo_L2OrderBook proto.InternalMessageInfo

func (m *L2OrderBook) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *L2OrderBook) GetBid() []*L2OrderBookItem {
	if m != nil {
		return m.Bid
	}
	return nil
}

func (m *L2OrderBook) GetAsk() []*L2OrderBookItem {
	if m != nil {
		return m.Ask
	}
	return nil
}

func (m *L2OrderBook) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*L2OrderBookRequest)(nil), "L2OrderBookRequest")
	proto.RegisterType((*L2OrderBookItem)(nil), "L2OrderBookItem")
	proto.RegisterType((*L2OrderBook)(nil), "L2OrderBook")
}

func init() {
	proto.RegisterFile("quotes.proto", fileDescriptor_aa8c397fe3f70398)
}

var fileDescriptor_aa8c397fe3f70398 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0xcd, 0xb6, 0x5b, 0x74, 0xba, 0x7e, 0x10, 0x45, 0x42, 0x2f, 0x96, 0x9e, 0x7a, 0xca,
	0x4a, 0x3d, 0x78, 0x14, 0xf7, 0x22, 0x82, 0x20, 0x06, 0x4f, 0xe2, 0xa5, 0x75, 0xc7, 0x25, 0xb4,
	0x35, 0xdd, 0x24, 0x5d, 0xd0, 0xff, 0xe2, 0x7f, 0x95, 0xa6, 0x5d, 0x29, 0xca, 0xde, 0xf2, 0x4c,
	0x5e, 0xde, 0x19, 0x1e, 0x98, 0xad, 0x5b, 0x65, 0xd1, 0xf0, 0x46, 0x2b, 0xab, 0xa2, 0x8b, 0x95,
	0x52, 0xab, 0x0a, 0xe7, 0x8e, 0x8a, 0xf6, 0x7d, 0x6e, 0x65, 0x8d, 0xc6, 0xe6, 0x75, 0xd3, 0x07,
	0x92, 0x57, 0xa0, 0x0f, 0xd9, 0xa3, 0x5e, 0xa2, 0x5e, 0x28, 0x55, 0x0a, 0x5c, 0xb7, 0x68, 0x2c,
	0x3d, 0x87, 0xc0, 0x7c, 0xd6, 0x85, 0xaa, 0x18, 0x89, 0x49, 0x7a, 0x20, 0x06, 0xa2, 0x14, 0x7c,
	0x23, 0xbf, 0x90, 0x4d, 0x62, 0x92, 0x1e, 0x0a, 0xf7, 0xa6, 0x11, 0xec, 0xcb, 0x0f, 0x8b, 0x7a,
	0x93, 0x57, 0xcc, 0x73, 0xf3, 0x5f, 0x4e, 0x6e, 0xe0, 0x78, 0xd4, 0x7e, 0x6f, 0xb1, 0xa6, 0x67,
	0x30, 0x6d, 0xb4, 0x7c, 0xc3, 0xa1, 0xb9, 0x87, 0x6e, 0xe1, 0x46, 0x55, 0x6d, 0xdd, 0x57, 0xfb,
	0x62, 0xa0, 0xe4, 0x9b, 0x40, 0x38, 0x6a, 0xd8, 0x79, 0x58, 0x02, 0x5e, 0x21, 0x97, 0x6c, 0x12,
	0x7b, 0x69, 0x98, 0x9d, 0xf0, 0x3f, 0x4b, 0x45, 0xf7, 0xd9, 0x65, 0x72, 0x53, 0x32, 0x6f, 0x57,
	0x26, 0x37, 0x25, 0xe5, 0xe0, 0x77, 0x86, 0x98, 0x1f, 0x93, 0x34, 0xcc, 0x22, 0xde, 0xeb, 0xe3,
	0x5b, 0x7d, 0xfc, 0x79, 0xab, 0x4f, 0xb8, 0x5c, 0x76, 0x0b, 0xc1, 0x93, 0xf3, 0x4d, 0xaf, 0xe1,
	0xe8, 0x0e, 0xed, 0xf8, 0xd6, 0x53, 0xfe, 0xdf, 0x6c, 0x34, 0x1b, 0x0f, 0x93, 0xbd, 0x4b, 0xb2,
	0x98, 0xbe, 0x78, 0x79, 0x23, 0x8b, 0xc0, 0xed, 0xb8, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0x32,
	0x48, 0xbe, 0x6e, 0xc0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// QuotesClient is the client API for Quotes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QuotesClient interface {
	GetL2OrderBook(ctx context.Context, in *L2OrderBookRequest, opts ...grpc.CallOption) (Quotes_GetL2OrderBookClient, error)
}

type quotesClient struct {
	cc grpc.ClientConnInterface
}

func NewQuotesClient(cc grpc.ClientConnInterface) QuotesClient {
	return &quotesClient{cc}
}

func (c *quotesClient) GetL2OrderBook(ctx context.Context, in *L2OrderBookRequest, opts ...grpc.CallOption) (Quotes_GetL2OrderBookClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Quotes_serviceDesc.Streams[0], "/Quotes/GetL2OrderBook", opts...)
	if err != nil {
		return nil, err
	}
	x := &quotesGetL2OrderBookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Quotes_GetL2OrderBookClient interface {
	Recv() (*L2OrderBook, error)
	grpc.ClientStream
}

type quotesGetL2OrderBookClient struct {
	grpc.ClientStream
}

func (x *quotesGetL2OrderBookClient) Recv() (*L2OrderBook, error) {
	m := new(L2OrderBook)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// QuotesServer is the server API for Quotes service.
type QuotesServer interface {
	GetL2OrderBook(*L2OrderBookRequest, Quotes_GetL2OrderBookServer) error
}

// UnimplementedQuotesServer can be embedded to have forward compatible implementations.
type UnimplementedQuotesServer struct {
}

func (*UnimplementedQuotesServer) GetL2OrderBook(req *L2OrderBookRequest, srv Quotes_GetL2OrderBookServer) error {
	return status.Errorf(codes.Unimplemented, "method GetL2OrderBook not implemented")
}

func RegisterQuotesServer(s *grpc.Server, srv QuotesServer) {
	s.RegisterService(&_Quotes_serviceDesc, srv)
}

func _Quotes_GetL2OrderBook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(L2OrderBookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuotesServer).GetL2OrderBook(m, &quotesGetL2OrderBookServer{stream})
}

type Quotes_GetL2OrderBookServer interface {
	Send(*L2OrderBook) error
	grpc.ServerStream
}

type quotesGetL2OrderBookServer struct {
	grpc.ServerStream
}

func (x *quotesGetL2OrderBookServer) Send(m *L2OrderBook) error {
	return x.ServerStream.SendMsg(m)
}

var _Quotes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Quotes",
	HandlerType: (*QuotesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetL2OrderBook",
			Handler:       _Quotes_GetL2OrderBook_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "quotes.proto",
}
